# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
# A Tera template to be rendered as the changelog's header.
# See https://keats.github.io/tera/docs/#introduction
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/docs/#introduction
body = """
{%- macro remote_url() -%}
    https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
{%- macro scoped(commit) -%}
    {% if commit.scope -%} *{{ commit.scope | split(pat="::") | first }}*: {% endif %}
{%- endmacro -%}
{%- macro first_message(commit) -%}
    {{ commit.message | split(pat="\n") | first | upper_first | trim_end }}
{%- endmacro -%}
{%- macro print_commit(commit) -%}
    - {{ self::scoped(commit=commit) }}\
        {{ self::first_message(commit=commit) }}\
        {% if commit.remote.pr_number %} ([#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }})){% endif %}
{%- endmacro -%}

{% if version %}\
    ## [{{ version }}]

    Released on: {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [Unreleased]
{% endif %}
{% if commits | filter(attribute="breaking", value=true) | length != 0 %}\
    ### Breaking Changes
    {% for commit in commits| filter(attribute="breaking", value=true) %}
        - {{ self::scoped(commit=commit) }}\
            {{ self::first_message(commit=commit) }}\
            {% if commit.remote.pr_number %} ([#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }})){% endif %}
            {% raw %}  {% endraw %}- **BREAKING CHANGE**: {{ commit.breaking_description }}
    {% endfor -%}
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}

    {% for commit in commits %}
        {%- if commit.scope -%}
        {% else -%}
            {{ self::print_commit(commit=commit) }}
        {% endif -%}
    {%- endfor -%}
    {%- for commit in commits | filter(attribute="scope") | sort(attribute="scope") -%}
        {{ self::print_commit(commit=commit) }}
    {% endfor -%}
{% endfor %}
### Commit Statistics\n
- {{ statistics.commit_count }} commit(s) contributed to the release.
- {{ statistics.commits_timespan | default(value=0) }} day(s) passed between the first and last commit.
{%- if statistics.days_passed_since_last_release %}
	- {{ statistics.days_passed_since_last_release }} day(s) passed between releases.
{%- endif %}

{% if version %}\
    [{{ version }}]({{ self::remote_url() }}/compare/{{ previous.version }}..{{ version }})
{% else %}\
    [Unreleased]: {{ self::remote_url() }}/compare/{{ previous.version }}..HEAD
{% endif %}\n
"""
# A Tera template to be rendered as the changelog's footer.
# See https://keats.github.io/tera/docs/#introduction
footer = """
<!-- generated by git-cliff -->
"""
# Remove leading and trailing whitespaces from the changelog's body.
trim = true

[git]
# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = true
# Exclude commits that do not match the conventional commits specification.
filter_unconventional = false
commit_preprocessors = [
    # Remove the "(#XXX)" that gets added in the default squash merge message in the github web interface
    { pattern = '\(#\d+\)', replace = "" }
]
# An array of regex based parsers for extracting data from the commit message.
# Assigns commits to groups.
# Optionally sets the commit's scope and can decide to exclude commits from further processing.
# HTML comments are used for group order, as groups are sorted alphabetically.
commit_parsers = [
    { message = "^feat", group = "<!-- 1 -->Features" },
    { message = "^fix", group = "<!-- 2 -->Bug Fixes" },
    { message = "^docs", group = "<!-- 7 -->Documentation" },
    { message = "^perf", group = "<!-- 3 -->Performance" },
    { message = "^refactor", group = "<!-- 5 -->Refactor" },
    # Style changes dont need to be mentioned
    { message = "^style", group = "Styling", skip = true },
    { message = "^test", group = "<!-- 6 -->Testing" },
    # Release commits dont add anything noteworthy to add to a changelog
    { message = "^chore\\(release\\): prepare for", skip = true },
    { message = "^chore", group = "<!-- 5 -->Miscellaneous Tasks" },
    # Merge commits themself dont add anything noteworthy
    { message = "^[mM]erge", skip = true },
    { message = "^[rR]evert", group = "<!-- 8 -->Revert" },
    { message = "^deps", group = "<!-- 4 -->Dependencies" },
    { body = ".*security", group = "<!-- 0 -->Security" },
    { body = ".*", group = "<!-- 99 -->Other (unconventional)" },
]
# Any commit that contains "BREAKING CHANGE" will be protected from being filtered out.
protect_breaking_commits = true
# Exclude commits that are not matched by any commit parser.
filter_commits = false
# Order releases topologically instead of chronologically.
topo_order = false
# Order of commits in each group/release within the changelog.
# Allowed values: newest, oldest
sort_commits = "oldest"

[bump]
# If this would be "true", it would immediately push us to "1.0.0" instead
# of continuing to use "0." based versions.
breaking_always_bump_major = false
