name: Release
on:
  push:
    tags:
      - 'v[0-99]+.[0-99]+.[0-99]+'
    branches: # validate workflow works as expected
      - "*"

env:
  BIN_NAME: termusic
  BIN_NAME_SERVER: termusic-server
  PROJECT_NAME: termusic

jobs:
  dist:
    name: Dist
    runs-on: ${{ matrix.build.os }}
    strategy:
      fail-fast: false # don't fail other jobs if one fails
      matrix:
        rust: [stable]
        build:
          # linux x86
          - archive: x86_64-linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          # linux arm64
          - archive: aarch64-linux
            os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          # mac x86
          - archive: x86_64-macos
            os: macos-latest
            target: x86_64-apple-darwin
          # mac arm64
          - archive: aarch64-macos
            os: macos-latest
            target: aarch64-apple-darwin
          # windows x86
          - archive: x86_64-windows
            os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.build.target }}

      - name: Install developer package dependencies (Linux)
        if: runner.os == 'linux'
        run: sudo apt-get update && sudo apt-get install libasound2-dev libdbus-1-dev pkg-config protobuf-compiler libgstreamer1.0-0 libunwind-dev libgstreamer1.0-dev libmpv-dev

      - name: Install developer package dependencies (MacOS)
        if: runner.os == 'macos'
        run: |
            brew update
            brew install protobuf

      - name: Install developer package dependencies (Windows)
        if: runner.os == 'windows'
        run: choco install protoc

      - name: Run cargo test
        run: cargo test --release --target ${{ matrix.build.target }}

      - name: Build release binary (Linux)
        if: runner.os == 'linux'
        run: cargo build --features cover,all-backends,rusty-soundtouch --release --all --target ${{ matrix.build.target }}

      - name: Build release binary (MacOS)
        if: runner.os == 'macos'
        run: cargo build --features rusty-soundtouch,rusty-simd --release --all --target ${{ matrix.build.target }}

      - name: Build release binary (Windows)
        if: runner.os == 'windows'
        run: cargo build --features rusty-soundtouch --release --all --target ${{ matrix.build.target }}

      - name: Strip release binary (Linux & MacOS)
        if: runner.os == 'linux' || runner.os == 'macos'
        run: |
          strip "target/${{ matrix.build.target }}/release/$BIN_NAME"
          strip "target/${{ matrix.build.target }}/release/$BIN_NAME_SERVER"

      - name: Build archive (Windows)
        if: runner.os == 'windows'
        run: |
          mkdir dist
          cp "target/${{ matrix.build.target }}/release/$BIN_NAME.exe" "dist/"
          cp "target/${{ matrix.build.target }}/release/$BIN_NAME_SERVER.exe" "dist/"

      - name: Build archive (Unix)
        if: runner.os != 'windows'
        shell: bash
        run: |
          mkdir dist
          cp "target/${{ matrix.build.target }}/release/$BIN_NAME" "dist/"
          cp "target/${{ matrix.build.target }}/release/$BIN_NAME_SERVER" "dist/"

      - uses: actions/upload-artifact@v7
        with:
          name: bins-${{ matrix.build.archive }}
          path: dist

  publish:
    name: Publish
    needs: [dist]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/download-artifact@v8

      - run: ls -al bins-*

      - name: Calculate tag name
        run: |
          name=dev
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            name=${GITHUB_REF:10}
          fi
          echo "name=val::$name" >> $GITHUB_OUTPUT
          echo "TAG=$name" >> $GITHUB_ENV
        id: tagname

      - name: Build archive
        shell: bash
        run: |
          set -ex

          rm -rf tmp
          mkdir tmp
          mkdir dist

          for dir in bins-* ; do
              platform=${dir#"bins-"}
              if [[ $platform =~ "windows" ]]; then
                  exe=".exe"
              fi
              pkgname=$PROJECT_NAME-$TAG-$platform
              mkdir tmp/$pkgname
              cp LICENSE_MIT README.md tmp/$pkgname
              mv bins-$platform/$BIN_NAME$exe tmp/$pkgname
              mv bins-$platform/$BIN_NAME_SERVER$exe tmp/$pkgname
              chmod +x tmp/$pkgname/$BIN_NAME$exe
              chmod +x tmp/$pkgname/$BIN_NAME_SERVER$exe

              if [ "$exe" = "" ]; then
                  tar cJf dist/$pkgname.tar.xz -C tmp $pkgname
              else
                  (cd tmp && 7z a -r ../dist/$pkgname.zip $pkgname)
              fi
          done

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          # tag: ${{ steps.tagname.outputs.TAG }}
          tag: ${{ github.ref }}
          overwrite: true

      - name: Extract version
        id: extract-version
        run: |
          printf "name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
