name: Release
on:
  push:
    tags:
    - 'v[0-99]+.[0-99]+.[0-99]+'

env:
  BIN_NAME: termusic
  BIN_NAME_SERVER: termusic-server
  PROJECT_NAME: termusic

jobs:
  dist:
    name: Dist
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # don't fail other jobs if one fails
      matrix:
        build: [x86_64-linux, aarch64-linux, x86_64-macos, x86_64-windows, aarch64-macos] # x86_64-win-gnu, win32-msvc
        include:
        - build: x86_64-linux
          os: ubuntu-latest
          rust: stable
          target: x86_64-unknown-linux-gnu
        - build: aarch64-linux
          os: ubuntu-24.04-arm
          rust: stable
          target: aarch64-unknown-linux-gnu
        - build: x86_64-macos
          os: macos-latest
          rust: stable
          target: x86_64-apple-darwin
        - build: aarch64-macos
          os: macos-latest
          rust: stable
          target: aarch64-apple-darwin
        - build: x86_64-windows
          os: windows-latest
          rust: stable
          target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}

      - name: Install developer package dependencies
        if: matrix.build == 'x86_64-linux' || matrix.build == 'aarch64-linux'
        run: sudo apt-get update && sudo apt-get install libasound2-dev libdbus-1-dev pkg-config protobuf-compiler libgstreamer1.0-0 libunwind-dev libgstreamer1.0-dev libmpv-dev

      - name: Install developer package dependencies
        if: matrix.build == 'x86_64-macos' || matrix.build == 'aarch64-macos'
        run: | 
            brew update
            brew install protobuf
  
      - name: Install developer package dependencies
        if: matrix.build == 'x86_64-windows'
        run: choco install protoc 
      
      - name: Run cargo test (cargo)
        if: (matrix.build == 'x86_64-linux' || matrix.build == 'aarch64-linux' || matrix.build == 'x86_64-macos' || matrix.build == 'aarch64-macos' || matrix.build == 'x86_64-windows')
        run: cargo test --release --target ${{ matrix.target }}

      - name: Build release binary (cargo x86_64-linux and aarch64-linux)
        if: matrix.build == 'x86_64-linux' || matrix.build == 'aarch64-linux'
        run: cargo build --features cover,all-backends,rusty-soundtouch --release --all --target ${{ matrix.target }}

      - name: Build release binary (cargo x86_64-macos and aarch64-macos)
        if: matrix.build == 'x86_64-macos' || matrix.build == 'aarch64-macos'
        run: cargo build --features rusty-soundtouch,rusty-simd --release --all --target ${{ matrix.target }}

      - name: Build release binary (cargo x86_64-windows)
        if: matrix.build == 'x86_64-windows'
        run: cargo build --features rusty-soundtouch --release --all --target ${{ matrix.target }}

      - name: Strip release binary (linux and macos)
        if: matrix.build == 'x86_64-linux' || matrix.build == 'aarch64-linux' || matrix.build == 'x86_64-macos' || matrix.build == 'aarch64-macos'
        run: |
          strip "target/${{ matrix.target }}/release/$BIN_NAME"
          strip "target/${{ matrix.target }}/release/$BIN_NAME_SERVER"

      - name: Build archive
        shell: bash
        run: |
          mkdir dist
          if [ "${{ matrix.os }}" = "windows-2019" ]; then
            cp "target/${{ matrix.target }}/release/$BIN_NAME.exe" "dist/"
            cp "target/${{ matrix.target }}/release/$BIN_NAME_SERVER.exe" "dist/"
          else
            cp "target/${{ matrix.target }}/release/$BIN_NAME" "dist/"
            cp "target/${{ matrix.target }}/release/$BIN_NAME_SERVER" "dist/"
          fi

      - uses: actions/upload-artifact@v7
        with:
          name: bins-${{ matrix.build }}
          path: dist

  publish:
    name: Publish
    needs: [dist]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/download-artifact@v8

      - run: ls -al bins-*

      - name: Calculate tag name
        run: |
          name=dev
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            name=${GITHUB_REF:10}
          fi
          echo "name=val::$name" >> $GITHUB_OUTPUT
          echo "TAG=$name" >> $GITHUB_ENV
        id: tagname

      - name: Build archive
        shell: bash
        run: |
          set -ex

          rm -rf tmp
          mkdir tmp
          mkdir dist

          for dir in bins-* ; do
              platform=${dir#"bins-"}
              if [[ $platform =~ "windows" ]]; then
                  exe=".exe"
              fi
              pkgname=$PROJECT_NAME-$TAG-$platform
              mkdir tmp/$pkgname
              cp LICENSE_MIT README.md tmp/$pkgname
              mv bins-$platform/$BIN_NAME$exe tmp/$pkgname
              mv bins-$platform/$BIN_NAME_SERVER$exe tmp/$pkgname
              chmod +x tmp/$pkgname/$BIN_NAME$exe
              chmod +x tmp/$pkgname/$BIN_NAME_SERVER$exe

              if [ "$exe" = "" ]; then
                  tar cJf dist/$pkgname.tar.xz -C tmp $pkgname
              else
                  (cd tmp && 7z a -r ../dist/$pkgname.zip $pkgname)
              fi
          done

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          # tag: ${{ steps.tagname.outputs.TAG }}
          tag: ${{ github.ref }}
          overwrite: true

      - name: Extract version
        id: extract-version
        run: |
          printf "name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
